---
# Installation
- name: "Installs bastille"
  pkgng:
    name: bastille
    state: present

- name: "Configures bastille"
  template:
    src: usr/local/etc/bastille/bastille.conf.j2
    dest: /usr/local/etc/bastille/bastille.conf

- name: "Enables bastille service"
  lineinfile:
    path: /etc/rc.conf
    regexp: "^bastille_enable.+$"
    line: 'bastille_enable="YES"'

# Networking
- name: "Setup cloned interfaces"
  lineinfile:
    path: /etc/rc.conf
    regexp: "^cloned_interfaces.+$"
    line: 'cloned_interfaces="lo1"'

- name: "Setup lo1 interface name"
  lineinfile:
    path: /etc/rc.conf
    regexp: "^ifconfig_lo1_name.+$"
    line: 'ifconfig_lo1_name="bastille0"'

- name: "Starts the cloned interface"
  command: 'service netif cloneup'

- name: "Configures pf"
  template:
    src: etc/pf.conf.j2
    dest: /etc/pf.conf

- name: "Enables pf service"
  lineinfile:
    path: /etc/rc.conf
    regexp: "^pf_enable.+$"
    line: 'pf_enable="YES"'

- name: "Starts pf"
  service:
    name: pf
    state: restarted

# Bootstrapping
- name: "Bootstraps Releases"
  command: 'bastille bootstrap {{ item }} update'
  loop: "{{ bastille_releases }}"
